name: Coverage Scores

on:
  pull_request:
      branches:
          - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run --source='.' --omit='*/tests/*,*/__init__.py,manage.py,*/*middleware.py' pytest
        coverage report
        coverage html

    - name: Create htmlcov zip
      run: zip -r htmlcov.zip htmlcov

    - name: Upload htmlcov as artifact
      uses: actions/upload-artifact@v4
      with:
        name: htmlcov-report
        path: htmlcov

    - name: Deploy coverage report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: htmlcov
        publish_branch: gh-pages
        commit_message: "Deploy coverage report"
