# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
on:
  push:
    branches:
      - main
    paths:
      - "doc/**.md"
      - "doc/imgs/**"

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: doc
          output_dir: pdfs
          images_dir: doc/imgs
          image_import: ./imgs
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: doc
          path: pdfs
